SistemaPresupuesto/Models/ErrorViewModel.cs
namespace SistemaPresupuesto.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SistemaPresupuesto/Models/TipoCuenta.cs
using System.ComponentModel.DataAnnotations;

namespace SistemaPresupuesto.Models
{
    public class TipoCuenta
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="El campo {0} es requerido")]
        //[StringLength(maximumLength:50, MinimumLength =3, ErrorMessage ="la longitud varia entre {2} y {1} caracteres")]
        public string Nombre { get; set; }
        public int UsuarioId { get; set; }
        public int Orden { get; set; }


        ///*pruebas de otras validaciones*/
        //[Required(ErrorMessage = "El campo {0} es requerido")]
        //[EmailAddress(ErrorMessage ="El campo {0} debe ser un correo electronico valido")]
        //public string Email { get; set; }

        //[Range(minimum:18,maximum:130,ErrorMessage ="el valor debe estar dentro de {1} y {2}")]
        //public int Edad { get; set; }

        //public string  Url { get; set; }

        //[CreditCard(ErrorMessage ="la tarjeta debe ser valida")]
        //[Display(Name ="Tarjeta de credito")]
        //public string TarjetaDeCredito { get; set; }
    }
}

SistemaPresupuesto/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaPresupuesto.Models;
using System.Diagnostics;

namespace SistemaPresupuesto.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            //comentario
            //otro mas
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaPresupuesto/Controllers/TiposCuentasController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaPresupuesto.Models;

namespace SistemaPresupuesto.Controllers
{
    public class TiposCuentasController : Controller
    {
        public IActionResult Crear()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Crear(TipoCuenta tipoCuenta)
        {
            if (!ModelState.IsValid)
            {
                return View(tipoCuenta);
            } 

            return View() ;
        }
    }
}

SistemaPresupuesto/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SistemaPresupuesto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaPresupuesto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaPresupuesto.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SistemaPresupuesto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SistemaPresupuesto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SistemaPresupuesto/Views/TiposCuentas/Crear.cshtml
@model TipoCuenta

@{
    ViewData["Title"] = "Crear tipo cuenta";
}


<h1>Crear tipo de cuenta</h1>
<h5>El tipo de cuenta se refiere a como agrupamos cuentas</h5>


<div asp-validation-summary="All" class="text-danger">
</div>

<form asp-controller="TiposCuentas" asp-action="Crear">
    <div class="mb-3">
        <label asp-for="Nombre" class="form-label"></label>
        <input type="text" asp-for="Nombre" class="form-control"/>
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}